BEGIN;
ALTER TABLE IF EXISTS source_documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS mitacs_projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS project_chunks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS import_runs DISABLE ROW LEVEL SECURITY;
COMMIT;

