import { DocumentRecord } from "../../lib/localMode";
import { CVAlignmentDraft, ProfileClaim } from "../../lib/ai/contracts";
import { formatCVExport } from "../../lib/ai/cvApproval";
import { Project } from "./types";
import { useFocusTrap } from "../../lib/useFocusTrap";
type Props = { project: Project; draft: CVAlignmentDraft; documents: DocumentRecord[]; accepted: string[]; rejected: string[]; onAccept: (key: string, claim: ProfileClaim) => void; onReject: (key: string) => void; onApprove: () => void; onClose: () => void };
export function CVAlignmentReview({ project, draft, documents, accepted, rejected, onAccept, onReject, onApprove, onClose }: Props) { const groups: Array<[string, ProfileClaim[]]> = [["Relevant skills", draft.reorderedSkills], ["Project bullets", draft.projectBullets], ["Research interests", draft.researchInterests]]; const trapRef = useFocusTrap<HTMLDivElement>(); return <div className="modal-backdrop"><div className="modal proposal-modal cv-modal" role="dialog" aria-modal="true" aria-labelledby="cv-align-title" tabIndex={-1} ref={trapRef}><button className="modal-close" onClick={onClose} aria-label="Close CV alignment">Close</button><p className="eyebrow">Evidence-backed draft</p><h2 id="cv-align-title">Align my CV</h2><p className="warning-note">Verify every statement before submission. This draft is separate from your original profile and CV.</p><p className="fine">Export buttons download Markdown files. Saving keeps an approved copy separately; it never overwrites your original profile.</p><div className="ai-review-summary"><strong>{accepted.length} accepted</strong><span>{rejected.length} rejected · {Math.max(0, 1 + draft.reorderedSkills.length + draft.projectBullets.length + draft.researchInterests.length - accepted.length - rejected.length)} unreviewed</span></div><h3>{project.title}</h3>{draft.summary && <CVClaim label="Tailored summary" claim={draft.summary} keyName="summary" documents={documents} accepted={accepted} rejected={rejected} onAccept={onAccept} onReject={onReject} />}{groups.map(([label, claims]) => <section key={label}><h3>{label}</h3>{claims.map((claim, index) => <CVClaim key={label + ":" + index} label={label} claim={claim} keyName={label + ":" + index} documents={documents} accepted={accepted} rejected={rejected} onAccept={onAccept} onReject={onReject} />)}</section>)}<section><h3>Suggested keywords</h3><p>{draft.suggestedKeywords.join(", ") || "None proposed"}</p><small>Keywords are suggestions, not verified facts.</small><h3>Evidence-backed gaps</h3>{draft.gapAnalysis.map((gap) => <p key={gap}>{gap}</p>)}<small>Gaps describe missing evidence; they are not claims.</small><h3>Questions</h3>{draft.questions.map((question) => <p key={question}>{question}</p>)}</section><div className="settings-actions"><button className="button secondary" onClick={onClose}>Keep original</button><button className="button secondary" onClick={() => exportDraft(project, draft, "full", accepted)}>Export full draft (.md)</button><button className="button secondary" onClick={() => exportDraft(project, draft, "approved", accepted)}>Export approved only (.md)</button><button className="button primary" onClick={onApprove} disabled={!accepted.length}>Save approved draft locally</button></div></div></div>; }
function CVClaim({ label, claim, keyName, documents, accepted, rejected, onAccept, onReject }: { label: string; claim: ProfileClaim; keyName: string; documents: DocumentRecord[]; accepted: string[]; rejected: string[]; onAccept: (key: string, claim: ProfileClaim) => void; onReject: (key: string) => void }) { const state = accepted.includes(keyName) ? "accepted" : rejected.includes(keyName) ? "rejected" : "proposed"; return <div className={"proposal-claim " + state}><span>{label}</span><strong>{claim.text}</strong><small>Sources: {claim.sourceIds.map((id) => documents.find((doc) => doc.id === id)?.name || id).join(", ")} · confidence {Math.round(claim.confidence * 100)}%</small><div className="claim-actions"><button className="link-button" onClick={() => onAccept(keyName, claim)} disabled={state === "accepted"}>Accept</button><button className="link-button" onClick={() => onReject(keyName)} disabled={state === "rejected"}>Reject</button></div></div>; }
function exportDraft(project: Project, draft: CVAlignmentDraft, mode: "full" | "approved", accepted: string[]) { const blob = new Blob([formatCVExport(project, draft, mode, accepted)], { type: "text/markdown" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "cv-alignment-" + project.project_id + "-" + mode + ".md"; link.click(); URL.revokeObjectURL(link.href); }
