import { ChangeEvent, KeyboardEvent, useState } from "react";
import { Profile } from "../../lib/localMode";
type ProfileReviewProps = { profile: Profile | null; onChange: (field: keyof Profile, value: string) => void; onContinue: () => void; onBack: () => void; onImprove: () => void; canImprove: boolean; hasKey: boolean; onOpenSettings: () => void };
export function ProfileReview({ profile, onChange, onContinue, onBack, onImprove, canImprove, hasKey, onOpenSettings }: ProfileReviewProps) { return <section className="screen profile-screen"><div className="editorial-main"><div className="screen-intro"><div><p className="eyebrow">Profile review</p><h1>Make the evidence legible.</h1><p>These summaries come from your local sources. Edit them freely before finding matching projects.</p></div><div className="profile-actions"><button className="button primary" onClick={onContinue} disabled={!profile}>Find matching projects <span aria-hidden="true">→</span></button>{canImprove ? <button className="button secondary" onClick={onImprove}>Review profile with AI</button> : hasKey ? <span className="optional-action-note">AI review is optional and needs a parsed evidence source first.</span> : <button className="button secondary" onClick={onOpenSettings}>Add a session key</button>}</div></div>{profile ? <div className="profile-content"><div className="profile-groups">{(["skills", "tools", "domains", "methods"] as (keyof Profile)[]).map((field) => <KeywordField key={field} field={field} values={profile[field] as string[]} onChange={(values) => onChange(field, values.join(", "))} />)}</div><section className="evidence-claims"><div className="list-heading"><div><h2>Source-backed evidence</h2><p className="fine">These excerpts shaped the profile. They remain grounded in your documents.</p></div><span className="success-label">{profile.evidence.length} excerpts</span></div>{profile.evidence.length ? <div className="evidence-claim-list">{profile.evidence.map((claim, index) => <p key={index}>“{claim}”</p>)}</div> : <p className="fine">No evidence snippets were found yet.</p>}</section></div> : <div className="empty-state"><strong>Profile review comes after evidence.</strong><span>Add and parse at least one evidence source first.</span><button className="button secondary" onClick={onBack}>Back to Evidence</button></div>}</div><aside className="editorial-aside profile-aside"><section className="aside-lead"><h2>Your profile</h2><p>A working summary built from {profile?.evidence.length ?? 0} source-backed excerpts.</p></section><section className="missing-information"><h2>What is missing?</h2>{profile?.gaps.map((gap) => <p key={gap}>{gap}</p>) ?? <p className="fine">Build a profile to see review prompts.</p>}</section></aside></section>; }

function KeywordField({ field, values, onChange }: { field: keyof Profile; values: string[]; onChange: (values: string[]) => void }) {
  const [draft, setDraft] = useState("");
  function addValue(event: KeyboardEvent<HTMLInputElement>) { if (event.key !== "Enter") return; event.preventDefault(); const value = draft.trim(); if (!value) return; onChange(Array.from(new Set([...values, value]))); setDraft(""); }
  return <div className="profile-field"><span>{field}</span><div className="profile-pills">{values.map((value) => <button type="button" className="profile-pill" key={value} onClick={() => onChange(values.filter((item) => item !== value))} title={`Remove ${value}`}>{value}<b aria-hidden="true">×</b></button>)}</div><input aria-label={`Add ${field}`} placeholder={`Add ${field} and press Enter`} value={draft} onChange={(event: ChangeEvent<HTMLInputElement>) => setDraft(event.target.value)} onKeyDown={addValue} /><small>Enter adds a term. Select a pill to remove it.</small></div>;
}
