import { FormEvent, useState } from "react";
import { KeyStatus, PooledKey, Provider } from "../../lib/localMode";
import { useFocusTrap } from "../../lib/useFocusTrap";

const FREE_TIER_NOTE: Record<Provider, string> = {
  gemini: "Free tier: ~1,500 requests/day, 10-15 RPM per key, no card required. Best option for volume — add a few keys from different accounts.",
  openrouter: "Free tier: 50 requests/day with no credits ever purchased, 1,000/day once an account has bought $10+ in credits. 20 RPM.",
  huggingface: "Free tier limits are variable and unpublished by Hugging Face - roughly a few hundred requests/hour, best-effort.",
  openai: "No free tier - each key needs a funded OpenAI account.",
};

const statusLabel: Record<KeyStatus, string> = { untested: "Untested", valid: "Valid", "rate-limited": "Rate-limited", invalid: "Invalid" };

type Props = { provider: Provider; model: string; keyReady: boolean; keyPool: PooledKey[]; onProvider: (provider: Provider) => void; onModel: (model: string) => void; onAddKey: (label: string, value: string) => void; onRemoveKey: (id: string) => void; onClose: () => void; onConsent: () => void; onSmokeTest: () => void };
export function SettingsDialog({ provider, model, keyReady, keyPool, onProvider, onModel, onAddKey, onRemoveKey, onClose, onConsent, onSmokeTest }: Props) {
  const [label, setLabel] = useState("");
  const [value, setValue] = useState("");
  const trapRef = useFocusTrap<HTMLDivElement>();
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!value.trim()) return; onAddKey(label.trim() || `Key ${keyPool.length + 1}`, value.trim()); setLabel(""); setValue(""); }
  return <div className="modal-backdrop" onClick={onClose}><div className="modal settings-modal" role="dialog" aria-modal="true" aria-labelledby="settings-title" tabIndex={-1} ref={trapRef} onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={onClose} aria-label="Close settings">Close</button><p className="eyebrow">Optional settings</p><h2 id="settings-title">Provider configuration</h2><p className="modal-intro">Keys remain in sessionStorage, never sent anywhere except directly to the provider you choose. Saving a key makes no provider call by itself.</p><div className="settings-row"><label>Provider<select value={provider} onChange={(e) => onProvider(e.target.value as Provider)}><option value="openrouter">OpenRouter</option><option value="gemini">Gemini</option><option value="openai">OpenAI</option><option value="huggingface">Hugging Face</option></select></label><label>Model<input value={model} onChange={(e) => onModel(e.target.value)} /></label></div><p className="fine settings-tier-note">{FREE_TIER_NOTE[provider]}</p><div className="key-pool-list">{keyPool.length === 0 && <p className="fine">No keys added for {provider} yet. Add one or more below - multiple keys from different accounts let a long run keep going after one hits its rate limit.</p>}{keyPool.map((key) => <div className="key-pool-row" key={key.id}><span className={`key-status key-status-${key.status}`}>{statusLabel[key.status]}</span><strong>{key.label}</strong><span className="fine">{"*".repeat(6)}{key.value.slice(-4)}</span><button className="icon-button" onClick={() => onRemoveKey(key.id)} aria-label={`Remove ${key.label}`}>x</button></div>)}</div><form onSubmit={submit} className="settings-form"><div className="settings-row"><label>Key label<input value={label} onChange={(e) => setLabel(e.target.value)} placeholder={`e.g. "personal account", "acct-2"`} /></label><label>Session-only key<input aria-label="Provider API key" type="password" value={value} onChange={(e) => setValue(e.target.value)} placeholder="Paste an API key" autoComplete="off" /></label></div><div className="settings-actions"><button className="button primary" type="submit">Add key to pool</button></div></form><div className="consent-summary"><strong>Consent boundary</strong><p>No content is sent to a provider without a separate, unambiguous confirmation.</p><button className="text-action" onClick={onConsent}>Read consent policy</button>{keyReady && <button className="button secondary" onClick={onSmokeTest}>Run manual provider smoke test</button>}</div></div></div>; }
