import { AIProfileProposal, CVAlignmentDraft, ProfileClaim, RerankItem, RerankValidationOptions } from "./contracts";

const MAX_CLAIMS = 80;
const MAX_STRING = 2400;
function finite(value: unknown, min = 0, max = 1): value is number { return typeof value === "number" && Number.isFinite(value) && value >= min && value <= max; }
function boundedString(value: unknown, max = MAX_STRING): value is string { return typeof value === "string" && value.trim().length > 0 && value.length <= max; }
function stringList(value: unknown, maxItems = 20, maxLength = 240): value is string[] { return Array.isArray(value) && value.length <= maxItems && value.every((entry) => boundedString(entry, maxLength)); }
export function parseJson(text: string) { try { const cleaned = text.trim().replace(/^```(?:json)?\s*/i, "").replace(/```$/, "").trim(); return JSON.parse(cleaned); } catch { throw new Error("The provider response was not valid JSON."); } }
function validateClaim(value: unknown, sourceIds: Set<string>): ProfileClaim { const item = value as any; if (!item || !boundedString(item.text) || !finite(item.confidence) || !Array.isArray(item.sourceIds) || item.sourceIds.length < 1 || item.sourceIds.length > 10 || item.sourceIds.some((id: unknown) => typeof id !== "string" || !sourceIds.has(id)) || (item.status !== undefined && !["proposed", "approved", "rejected", "unsupported"].includes(item.status))) throw new Error("The provider returned a claim with invalid provenance."); return { text: item.text, confidence: item.confidence, sourceIds: item.sourceIds, status: item.status }; }
function validateClaimList(value: unknown, sourceIds: Set<string>) { if (!Array.isArray(value) || value.length > MAX_CLAIMS) throw new Error("The provider returned too many claims."); return value.map((entry) => validateClaim(entry, sourceIds)); }
export function validateProfileProposal(value: unknown, submittedSourceIds: string[] = []) : AIProfileProposal { const item = value as any; const sources = new Set(submittedSourceIds); if (!item || (item.headline !== null && validateClaim(item.headline, sources) === undefined) || !item.technicalSkills || typeof item.technicalSkills !== "object") throw new Error("The provider returned an unsupported profile proposal."); const technicalSkills: Record<string, ProfileClaim[]> = {}; Object.keys(item.technicalSkills).slice(0, 20).forEach((key) => { if (!boundedString(key, 80)) throw new Error("The provider returned an invalid skill category."); technicalSkills[key] = validateClaimList(item.technicalSkills[key], sources); }); const result = { headline: item.headline === null ? null : validateClaim(item.headline, sources), technicalSkills, researchInterests: validateClaimList(item.researchInterests, sources), experienceBullets: validateClaimList(item.experienceBullets, sources), projectSummaries: validateClaimList(item.projectSummaries, sources), measurableOutcomes: validateClaimList(item.measurableOutcomes, sources), strengths: validateClaimList(item.strengths, sources), missingInformation: stringList(item.missingInformation, 30, 300) ? item.missingInformation : [], questions: stringList(item.questions, 30, 500) ? item.questions : [] }; return result; }
export function validateRerank(value: unknown, options: RerankValidationOptions | Set<string>): RerankItem[] { const normalized = options instanceof Set ? { candidateIds: Array.from(options), requireComplete: false } : options; if (!Array.isArray(value) || value.length === 0 || value.length > normalized.candidateIds.length) throw new Error("The provider returned an invalid reranking set."); if (normalized.requireComplete && value.length !== normalized.candidateIds.length) throw new Error("The provider returned an incomplete reranking set."); const allowed = new Set(normalized.candidateIds); const seenIds = new Set<string>(); const seenRanks = new Set<number>(); const items = value.map((item: any) => { if (!item || typeof item.projectId !== "string" || !allowed.has(item.projectId) || seenIds.has(item.projectId) || !Number.isInteger(item.rank) || item.rank < 1 || item.rank > value.length || seenRanks.has(item.rank) || !finite(item.finalFitScore, 0, 100) || !stringList(item.matchedEvidence) || !stringList(item.missingEvidence) || !boundedString(item.whyItFits, 2000) || !stringList(item.emphasize) || !stringList(item.uncertainty)) throw new Error("The provider returned an unsupported reranking item."); seenIds.add(item.projectId); seenRanks.add(item.rank); return item as RerankItem; }); if (seenRanks.size !== value.length) throw new Error("The provider returned duplicate or non-contiguous ranks."); return items.sort((a, b) => a.rank - b.rank); }
export function validateCVAlignment(value: unknown, submittedSourceIds: string[] = []): CVAlignmentDraft { const item = value as any; const sources = new Set(submittedSourceIds); const list = (entry: unknown) => validateClaimList(entry, sources); if (!item || (item.summary !== null && !validateClaim(item.summary, sources)) || !Array.isArray(item.suggestedKeywords) || !stringList(item.suggestedKeywords, 40, 100) || !stringList(item.gapAnalysis, 40, 500) || !stringList(item.questions, 40, 500)) throw new Error("The provider returned an unsupported CV alignment draft."); return { summary: item.summary === null ? null : validateClaim(item.summary, sources), reorderedSkills: list(item.reorderedSkills), projectBullets: list(item.projectBullets), researchInterests: list(item.researchInterests), suggestedKeywords: item.suggestedKeywords, gapAnalysis: item.gapAnalysis, questions: item.questions }; }
